from src.utils.id import (
    get_app_regex,
    get_traffic_regex,
    AppName,
    TrafficName,
)


file_name_list = [
    "aim_chat_3a",
    "aim_chat_3b",
    "AIMchat1",
    "AIMchat2",
    "email1a",
    "email1b",
    "email2a",
    "email2b",
    "facebook_audio1a",
    "facebook_audio1b",
    "facebook_audio2a",
    "facebook_audio2b",
    "facebook_audio3",
    "facebook_audio4",
    "facebook_chat_4a",
    "facebook_chat_4b",
    "facebook_video1a",
    "facebook_video1b",
    "facebook_video2a",
    "facebook_video2b",
    "facebookchat1",
    "facebookchat2",
    "facebookchat3",
    "ftps_down_1a",
    "ftps_down_1b",
    "ftps_up_2a",
    "ftps_up_2b",
    "gmailchat1",
    "gmailchat2",
    "gmailchat3",
    "hangout_chat_4b",
    "hangouts_audio1a",
    "hangouts_audio1b",
    "hangouts_audio2a",
    "hangouts_audio2b",
    "hangouts_audio3",
    "hangouts_audio4",
    "hangouts_chat_4a",
    "hangouts_video1b",
    "hangouts_video2a",
    "hangouts_video2b",
    "ICQchat1",
    "ICQchat2",
    "netflix1",
    "netflix2",
    "netflix3",
    "netflix4",
    "p2p_vuze2-1",
    "p2p_vuze",
    "scp1",
    "scpDown1",
    "scpDown2",
    "scpDown3",
    "scpDown4",
    "scpDown5",
    "scpDown6",
    "scpUp1",
    "scpUp2",
    "scpUp3",
    "scpUp5",
    "scpUp6",
    "sftp1",
    "sftp_down_3a",
    "sftp_down_3b",
    "sftp_up_2a",
    "sftp_up_2b",
    "sftpDown1",
    "sftpDown2",
    "sftpUp1",
    "skype_audio1a",
    "skype_audio1b",
    "skype_audio2a",
    "skype_audio2b",
    "skype_audio3",
    "skype_audio4",
    "skype_chat_1a",
    "skype_chat_1b",
    "skype_file1",
    "skype_file2",
    "skype_file3",
    "skype_file4",
    "skype_file5",
    "skype_file6",
    "skype_file7",
    "skype_file8",
    "skype_video1a",
    "skype_video1b",
    "skype_video2a",
    "skype_video2b",
    "spotify1",
    "spotify2",
    "spotify3",
    "spotify4",
    "vimeo1",
    "vimeo2",
    "vimeo3",
    "vimeo4",
    "voipbuster1b",
    "voipbuster2b",
    "voipbuster3b",
    "voipbuster_4a",
    "voipbuster_4b",
    "vpn_aim_chat1a",
    "vpn_aim_chat1b",
    "vpn_bittorrent",
    "vpn_email2a",
    "vpn_email2b",
    "vpn_facebook_audio2",
    "vpn_facebook_chat1a",
    "vpn_facebook_chat1b",
    "vpn_ftps_A",
    "vpn_ftps_B",
    "vpn_hangouts_audio1",
    "vpn_hangouts_audio2",
    "vpn_hangouts_chat1a",
    "vpn_hangouts_chat1b",
    "vpn_icq_chat1a",
    "vpn_icq_chat1b",
    "vpn_netflix_A",
    "vpn_sftp_A",
    "vpn_sftp_B",
    "vpn_skype_audio1",
    "vpn_skype_audio2",
    "vpn_skype_chat1a",
    "vpn_skype_chat1b",
    "vpn_skype_file1a",
    "vpn_skype_file1b",
    "vpn_spotify_A",
    "vpn_vimeo_A",
    "vpn_vimeo_B",
    "vpn_voipbuster1a",
    "vpn_voipbuster1b",
    "vpn_youtube_A",
    "youtube1",
    "youtube2",
    "youtube3",
    "youtube4",
    "youtube5",
    "youtube6",
    "youtubeHTML5_1",
]


def test_get_app_id() -> None:
    for file_name in file_name_list:
        print(file_name)
        cnt = 0
        for id in range(len(AppName)):
            if get_app_regex(id).match(file_name):
                print(f"app: {AppName[id]}")
                cnt += 1
                pass
            continue
        assert cnt == 1
        cnt = 0
        for id in range(len(TrafficName)):
            if get_traffic_regex(id).match(file_name):
                print(f"traffic: {TrafficName[id]}")
                cnt += 1
                pass
            continue
        assert cnt == 1
        continue

    return None
